version: '3'
services:
  web:
    image: nginx
    depends_on:
      - db
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - ./content:/var/www/html
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "8080:80"
  php:
    image: php:fpm
    volumes:
      - ./content:/var/www/html
      - ./php:/usr/local/etc/php
  db:
    image: mysql
    restart: always
    environment:
        - MYSQL_DATABASE=webdev
        - MYSQL_ROOT_PASSWORD=DO_NOT_USE_IN_PROD
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=DO_NOT_USE_IN_PROD
    ports:
      - "6033:3306"
    volumes:
      - /dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: